const languages = [
    {
        no: "0",
        name: "Auto",
        native: "Detect",
        code: "auto",
    },
    {
        no: "1",
        name: "Afrikaans",
        native: "Afrikaans",
        code: "af",
    },
    {
        no: "2",
        name: "Albanian",
        native: "Shqip",
        code: "sq",
    },
    {
        no: "3",
        name: "Amharic",
        native: "አማርኛ",
        code: "am",
    },
    {
        no: "4",
        name: "Arabic",
        native: "عربى",
        code: "ar",
    },
    {
        no: "5",
        name: "Armenian",
        native: "Հայերէն",
        code: "hy",
    },
    {
        no: "6",
        name: "Azerbaijani",
        native: "آذربایجان دیلی",
        code: "az",
    },
    {
        no: "7",
        name: "Basque",
        native: "Euskara",
        code: "eu",
    },
    {
        no: "8",
        name: "Belarusian",
        native: "Беларуская",
        code: "be",
    },
    {
        no: "9",
        name: "Bengali",
        native: "বাংলা",
        code: "bn",
    },
    {
        no: "10",
        name: "Bosnian",
        native: "Bosanski",
        code: "bs",
    },
    {
        no: "11",
        name: "Bulgarian",
        native: "Български",
        code: "bg",
    },
    {
        no: "12",
        name: "Catalan",
        native: "Català",
        code: "ca",
    },
    {
        no: "13",
        name: "Cebuano",
        native: "Cebuano",
        code: "ceb",
    },
    {
        no: "14",
        name: "Chichewa",
        native: "Chichewa",
        code: "ny",
    },
    {
        no: "15",
        name: "Chinese (Simplified)",
        native: "中文简体",
        code: "zh-CN",
    },
    {
        no: "16",
        name: "Chinese (Traditional)",
        native: "中文繁體",
        code: "zh-TW",
    },
    {
        no: "17",
        name: "Corsican",
        native: "Corsu",
        code: "co",
    },
    {
        no: "18",
        name: "Croatian",
        native: "Hrvatski",
        code: "hr",
    },
    {
        no: "19",
        name: "Czech",
        native: "Čeština",
        code: "cs",
    },
    {
        no: "20",
        name: "Danish",
        native: "Dansk",
        code: "da",
    },
    {
        no: "21",
        name: "Dutch",
        native: "Nederlands",
        code: "nl",
    },
    {
        no: "22",
        name: "English",
        native: "English",
        code: "en",
    },
    {
        no: "23",
        name: "Esperanto",
        native: "Esperanto",
        code: "eo",
    },
    {
        no: "24",
        name: "Estonian",
        native: "Eesti keel",
        code: "et",
    },
    {
        no: "25",
        name: "Filipino",
        native: "Filipino",
        code: "tl",
    },
    {
        no: "26",
        name: "Finnish",
        native: "Suomi",
        code: "fi",
    },
    {
        no: "27",
        name: "French",
        native: "Français",
        code: "fr",
    },
    {
        no: "28",
        name: "Frisian",
        native: "Frysk",
        code: "fy",
    },
    {
        no: "29",
        name: "Galician",
        native: "Galego",
        code: "gl",
    },
    {
        no: "30",
        name: "Georgian",
        native: "ქართული",
        code: "ka",
    },
    {
        no: "31",
        name: "German",
        native: "Deutsch",
        code: "de",
    },
    {
        no: "32",
        name: "Greek",
        native: "Ελληνικά",
        code: "el",
    },
    {
        no: "33",
        name: "Gujarati",
        native: "ગુજરાતી",
        code: "gu",
    },
    {
        no: "34",
        name: "Haitian Creole",
        native: "Kreyòl ayisyen",
        code: "ht",
    },
    {
        no: "35",
        name: "Hausa",
        native: "Hausa",
        code: "ha",
    },
    {
        no: "36",
        name: "Hawaiian",
        native: "ʻŌlelo Hawaiʻi",
        code: "haw",
    },
    {
        no: "37",
        name: "Hebrew",
        native: "עברית",
        code: "iw",
    },
    {
        no: "38",
        name: "Hindi",
        native: "हिन्दी",
        code: "hi",
    },
    {
        no: "39",
        name: "Hmong",
        native: "Hmoob",
        code: "hmn",
    },
    {
        no: "40",
        name: "Hungarian",
        native: "Magyar",
        code: "hu",
    },
    {
        no: "41",
        name: "Icelandic",
        native: "Íslenska",
        code: "is",
    },
    {
        no: "42",
        name: "Igbo",
        native: "Igbo",
        code: "ig",
    },
    {
        no: "43",
        name: "Indonesian",
        native: "Bahasa Indonesia",
        code: "id",
    },
    {
        no: "44",
        name: "Irish",
        native: "Gaeilge",
        code: "id",
    },
    {
      no: "45",
      name: "Italian",
      native: "Italiano",
      code: "it",
  },
  {
    no: "46",
    name: "Japanese",
    native: "日本語",
    code: "ja",
},
{
  no: "47",
  name: "Javanese",
  native: "ꦧꦱꦗꦮ",
  code: "jv",
},
{
  no: "48",
  name: "Kannada",
  native: "ಕನ್ನಡ",
  code: "kn",
},
{
  no: "49",
  name: "Kazakh",
  native: "Қазақ тілі",
  code: "Қазақ тілі",
},
{
  no: "50",
  name: "Khmer",
  native: "ភាសាខ្មែរ",
  code: "km",
},
{
  no: "51",
  name: "Kinyarwanda",
  native: "Kinyarwanda",
  code: "id",
},
{
  no: "52",
  name: "Korean",
  native: "한국어",
  code: "id",
},
{
  no: "53",
  name: "Kurdish (Kurmanji)",
  native: "Kurdî (Kurmancî)",
  code: "id",
},
{
  no: "54",
  name: "Kyrgyz",
  native: "Кыргызча",
  code: "id",
},
{
  no: "55",
  name: "Lao",
  native: "ລາວ",
  code: "id",
},
{
  no: "56",
  name: "Latin",
  native: "Latine",
  code: "id",
},
{
  no: "57",
  name: "Latvian",
  native: "Latviešu",
  code: "id",
},
{
  no: "58",
  name: "Lithuanian",
  native: "Lietuvių",
  code: "id",
},
{
  no: "59",
  name: "Luxembourgish",
  native: "Lëtzebuergesch",
  code: "id",
},
{
  no: "60",
  name: "Macedonian",
  native: "Македонски",
  code: "id",
},
{
  no: "61",
  name: "Malagasy",
  native: "Malagasy",
  code: "id",
},
{
  no: "62",
  name: "Malay",
  native: "Bahasa Melayu",
  code: "id",
},
{
  no: "63",
  name: "Malayalam",
  native: "മലയാളം",
  code: "id",
},
{
  no: "64",
  name: "Maltese",
  native: "Malti",
  code: "id",
},
{
  no: "65",
  name: "Maori",
  native: "Te Reo Māori",
  code: "id",
},
{
  no: "66",
  name: "Marathi",
  native: "मराठी",
  code: "id",
},
{
  no: "67",
  name: "Mongolian",
  native: "Монгол",
  code: "id",
},
{
  no: "68",
  name: "Myanmar (Burmese)",
  native: "မြန်မာ (ဗမာ)",
  code: "id",
},
{
  no: "69",
  name: "Nepali",
  native: "नेपाली",
  code: "id",
},
{
  no: "70",
  name: "Norwegian",
  native: "Norsk",
  code: "id",
},
{
  no: "71",
  name: "Odia (Oriya)",
  native: "ଓଡ଼ିଆ",
  code: "id",
},
{
  no: "72",
  name: "Pashto",
  native: "پښتو",
  code: "id",
},
{
  no: "73",
  name: "Persian",
  native: "فارسی",
  code: "id",
},
{
  no: "74",
  name: "Polish",
  native: "Polski",
  code: "id",
},
{
  no: "75",
  name: "Portuguese",
  native: "Português",
  code: "id",
},
{
  no: "76",
  name: "Punjabi",
  native: "ਪੰਜਾਬੀ",
  code: "id",
},
{
  no: "77",
  name: "Romanian",
  native: "Română",
  code: "id",
},
{
  no: "78",
  name: "Russian",
  native: "Русский",
  code: "id",
},
{
  no: "79",
  name: "Samoan",
  native: "Gagana Samoa",
  code: "id",
},
{
  no: "80",
  name: "Scots Gaelic",
  native: "Gàidhlig",
  code: "id",
},
{
  no: "81",
  name: "Serbian",
  native: "Српски",
  code: "id",
},
{
  no: "82",
  name: "Sesotho",
  native: "Sesotho",
  code: "id",
},
{
  no: "83",
  name: "Shona",
  native: "ChiShona",
  code: "id",
},
{
  no: "84",
  name: "Sindhi",
  native: "سنڌي",
  code: "id",
},
{
  no: "85",
  name: "Sinhala",
  native: "සිංහල",
  code: "id",
},
{
  no: "86",
  name: "Slovak",
  native: "Slovenčina",
  code: "id",
},
{
  no: "87",
  name: "Slovenian",
  native: "Slovenščina",
  code: "id",
},
{
  no: "88",
  name: "Somali",
  native: "Soomaali",
  code: "id",
},
{
  no: "89",
  name: "Spanish",
  native: "Español",
  code: "id",
},
{
  no: "90",
  name: "Sundanese",
  native: "Basa Sunda",
  code: "id",
},
{
  no: "91",
  name: "Swahili",
  native: "Kiswahili",
  code: "id",
},
{
  no: "92",
  name: "Swedish",
  native: "Svenska",
  code: "id",
},
{
  no: "93",
  name: "Tajik",
  native: "Тоҷикӣ",
  code: "id",
},
{
  no: "94",
  name: "Tamil",
  native: "தமிழ்",
  code: "id",
},
{
  no: "95",
  name: "Tatar",
  native: "Татарча",
  code: "id",
},
{
  no: "96",
  name: "Telugu",
  native: "తెలుగు",
  code: "id",
},
{
  no: "97",
  name: "Thai",
  native: "ไทย",
  code: "id",
},
{
  no: "98",
  name: "Turkish",
  native: "Türkçe",
  code: "id",
},
{
  no: "99",
  name: "Turkmen",
  native: "Türkmençe",
  code: "id",
},
{
  no: "100",
  name: "Ukrainian",
  native: "Українська",
  code: "id",
},
{
  no: "101",
  name: "Urdu",
  native: "اردو",
  code: "id",
},
{
  no: "102",
  name: "Uyghur",
  native: "ئۇيغۇرچە",
  code: "id",
},
{
  no: "103",
  name: "Uzbek",
  native: "Oʻzbekcha",
  code: "id",
},
{
  no: "104",
  name: "Vietnamese",
  native: "Tiếng Việt",
  code: "id",
},
{
  no: "105",
  name: "Welsh",
  native: "Cymraeg",
  code: "id",
},
{
  no: "106",
  name: "Xhosa",
  native: "isiXhosa",
  code: "id",
},
{
  no: "107",
  name: "Yiddish",
  native: "ייִדיש",
  code: "id",
},
{
  no: "108",
  name: "Yoruba",
  native: "Yorùbá",
  code: "id",
},
{
  no: "109",
  name: "Zulu",
  native: "isiZulu",
  code: "id",
},
];
